# Change these first
owner: GitJaxder # Your GitHub organization or username, where this repository lives
repo: legendary-lamp # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Minecraft Server
    url: modded.minecraft.jaxder.com
    check: "tcp-ping"
    port: 38754
  - name: Plex
    url: https://server.plex.jareddsharp.com/identity

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.jareddsharp.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status of Jared's Servers
  introTitle: "This site was built using **Upptime**, the open-source uptime monitor and status page, powered entirely by GitHub."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
