# Change these first
owner: GitJaxder # Your GitHub organization or username, where this repository lives
repo: legendary-lamp # The name of this repository

sites:
  - name: Plex
    url: $PLEX_URL
  - name: Plex Requests
    url: plex.jareddsharp.com
  - name: Minecraft Server
    url: modded.minecraft.jaxder.com
    check: "tcp-ping"
    port: 38754
  - name: Palworld Server
    url: games.jaxder.com
    check: "udp-ping"
    port: 38572
  - name: Valheim Server
    url: games.jaxder.com
    check: "tcp-ping"
    port: 2456
  - name: Project Zomboid Server
    url: games.jaxder.com
    check: "udp-ping"
    port: 16261

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.jareddsharp.com
  theme: ocean
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status of Jared's Servers
  introTitle: "This site was built using **Upptime**, the open-source uptime monitor and status page, powered entirely by GitHub."
  navbar:
    - title: Status
      href: /
    - title: Speedtest
      href: https://speedtest.jareddsharp.com
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
